---
- name: Restart firewalld
  become: true
  become_user: root
  service:
    name: firewalld
    enabled: true
    state: restarted

- name: Restart postfix
  become: true
  become_user: root
  systemd:
    name: postfix
    daemon_reload: true
    enabled: true
    state: started

- name: Restart sshd
  become: true
  become_user: root
  debug:
    msg: "checking /etc/ssh/sshd_config first"
  changed_when: true
  notify:
    - Check sshd configuration
    - Restart sshd - after config check

- name: Check sshd configuration
  become: true
  become_user: root
  command: '/usr/sbin/sshd -t'
  register: sshd_config
  changed_when: "sshd_config.rc != 0"

- name: Restart sshd - after config check
  become: true
  become_user: root
  service:
    name: sshd
    state: restarted
...
