---
- name: Converge
  hosts: all
  become: true
  vars:
    role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    server:
      install: true
      packages:
        - openssh-server
        - postfix

  tasks:
    - name: "Include {{ role_name }}"
      ansible.builtin.include_role:
        name: "{{ role_name }}"
...
